// ignore_for_file: prefer_const_constructors

import 'package:auto_route/auto_route.dart';
import 'package:shift/presentation/core/app_router.gr.dart';

@AutoRouterConfig()
class AppRouter extends RootStackRouter {

  @override
  List<AutoRoute> get routes => [
        AutoRoute(page: SplashPage.page, initial: true),
        AutoRoute(page: Onboarding1.page),
        AutoRoute(page: Onboarding2.page),
        AutoRoute(page: OnBoarding3.page),
        AutoRoute(page: LoginPage.page),
        AutoRoute(page: RegisterPage.page),
        AutoRoute(page: RegisterProfilePage.page),
        AutoRoute(page: LocationDetailForm.page),
        AutoRoute(page: AddContractorSkillsForm.page),
        AutoRoute(page: EducationListScreen.page),
        AutoRoute(page: AddEducationDetailScreen.page),
        AutoRoute(page: AddExperienceDetailScreen.page),
        AutoRoute(page: ReferenceListScreen.page),
        AutoRoute(page: AddReferenceDetailScreen.page),
        AutoRoute(page: DocumentPageScreen.page),
        AutoRoute(page: LegalScreeningQuestionsPage.page),
        AutoRoute(page: TermsAndConditionsScreen.page),
        AutoRoute(page: IntroVideoScreen.page),
        AutoRoute(page: IntroQuizScreen.page),
        AutoRoute(page: AddCardDetailPage.page),
        AutoRoute(page: LocationExample.page),
        AutoRoute(page: AddBankDetailsScreen.page),
        AutoRoute(page: ViewHomeShiftDetails.page),
        AutoRoute(page: ViewDates.page),
        AutoRoute(page: HealthCarePostForm.page),
        AutoRoute(page: HealthcarePostShift.page),
        AutoRoute(page: ViewSingleApplicants.page),
        AutoRoute(page: AddCardView.page),
        AutoRoute(page: ViewApplicantProfile.page),
        AutoRoute(page: ProfessionalReferenceDetail.page),
        AutoRoute(page: PersonalReferenceDetail.page),
        AutoRoute(page: CommonDocumentView.page),
        AutoRoute(page: TotalPraposalView.page),
        AutoRoute(page: ViewPersonPraposalView.page),
        AutoRoute(page: CounterPurposeView.page),
        AutoRoute(page: AwaitingConfirmationView.page),
        AutoRoute(page: TeamsView.page),
        AutoRoute(page: AddNewTeamView.page),
        AutoRoute(page: TeamDetailView.page),
        AutoRoute(page: AddNewMemberView.page),
        AutoRoute(page: PostShiftRecurring.page),
        AutoRoute(page: ReviewPostShiftDetail.page),
        AutoRoute(page: PayableDetail.page),
        AutoRoute(page: AddMultiDateTime.page),
        AutoRoute(page: PrivacyPolicyScreen.page),
        AutoRoute(page: AddSpecialityExperience.page),
        AutoRoute(page: QuizResultScreen.page),
        AutoRoute(page: ShowGoogleMap.page),
        AutoRoute(page: ContractorMainTabView.page),
        AutoRoute(page: ContractorHomeView.page),
        AutoRoute(page: SendProposal.page),
        AutoRoute(page: ProposeAvailability.page),
        AutoRoute(page: ContractorShiftView.page),
        AutoRoute(page: ViewUpcomingShiftDetails.page),
        AutoRoute(page: ViewContractorShift.page),
        AutoRoute(page: ViewContractorShiftDates.page),
        AutoRoute(page: ViewFilledShiftsDetails.page),
        AutoRoute(page: ViewFilledShiftsDates.page),
        AutoRoute(page: ViewAgreedPraposal.page),
        AutoRoute(page: PreviousShiftView.page),
        AutoRoute(page: EditProfileView.page),
        AutoRoute(page: ShiftActionsView.page),
        AutoRoute(page: ProposalReceived.page),
        AutoRoute(page: MyCalendarView.page),
        AutoRoute(page: FilledHiredContractorList.page),
        AutoRoute(page: AgreedProposal.page),
        AutoRoute(page: SingleAgreedShift.page),
        AutoRoute(page: MultiAgreedShift.page),
        AutoRoute(page: ApprovedHiredList.page),
        AutoRoute(page: CancelledContractorList.page),
        AutoRoute(page: ProfessionalProfileView.page),
        AutoRoute(page: PersonalProfileView.page),
        AutoRoute(page: EducationProfileListView.page),
        AutoRoute(page: EmployerAvailabilityView.page),
        AutoRoute(page: HiredContractorView.page),
        AutoRoute(page: EmployerLocationFormView.page),
        AutoRoute(page: EmployerLocationView.page),
        AutoRoute(page: ChangePasswordView.page),
        AutoRoute(page: AccountManagementView.page),
        AutoRoute(page: BillingView.page),
        AutoRoute(page: InvoiceDetailView.page),
        AutoRoute(page: InvoiceView.page),
        AutoRoute(page: MonthlyStatementView.page),
        AutoRoute(page: PaymentHistoryView.page),
        AutoRoute(page: PaymentHistoryView.page),
        AutoRoute(page: PaymentMethodView.page),
        AutoRoute(page: PreviousShiftAllView.page),
        AutoRoute(page: AboutView.page),
        AutoRoute(page: CancellationPolicyView.page),
        AutoRoute(page: FaqView.page),
        AutoRoute(page: SupportTicketView.page),
        AutoRoute(page: CustomerSupportView.page),
        AutoRoute(page: ContractorEarningView.page),
        AutoRoute(page: ContractorStatementView.page),
        AutoRoute(page: ContractorTotalEarningView.page),
        AutoRoute(page: ContractorWalletView.page),
        AutoRoute(page: ContractorWithdrawPaymentView.page),
        AutoRoute(page: ContractorPreviousShiftView.page),
        AutoRoute(page: ContractorPerformanceInsightView.page),
        AutoRoute(page: ContractorPerformanceInsightView.page),
        AutoRoute(page: ContractorRatingView.page),
        AutoRoute(page: ReferColleagueView.page),
        AutoRoute(page: ContractorUpdateProfileView.page),
        AutoRoute(page: BankListView.page),
        AutoRoute(page: ReferenceListView.page),
        // AutoRoute(page: FullTimePositionView.page),
        // AutoRoute(page: FullPositionDetailView.page),

        AutoRoute(page: EmployerFullPostingView.page),
        AutoRoute(page: EmployerFullPostingConfirmView.page),
        AutoRoute(page: EmployerFullPostingReviewView.page),
        AutoRoute(page: EmployerFullPositionAddView.page),

        AutoRoute(page: EmployerLongTermView.page),
        AutoRoute(page: EmployerLongTermPositionDetailView.page),
        AutoRoute(page: EmployerLongTermPositionAddView.page),
        AutoRoute(page: EmployerLongTermPositionAddDetailView.page),
        AutoRoute(page: EmployerLongTermApplicantView.page),
        AutoRoute(page: EmployerLongTermPostConfirmationView.page),
        AutoRoute(page: EmployerLongTermReviewDetailView.page),
        AutoRoute(page: EmployerLongTermPayableView.page),
        AutoRoute(page: EmployerLongTermAuthorizePaymentView.page),

        AutoRoute(page: ContractorFullTimePositionView.page),
        AutoRoute(page: ContractorFullTimePositionDetailView.page),
        AutoRoute(page: ContractorLongTermView.page),



        AutoRoute(page: EmployerCompletedShiftView.page),
        AutoRoute(page: SaveTemplateView.page),
        AutoRoute(page: ViewCollegueProfile.page),
        AutoRoute(page: AddressProofScreen.page),
        AutoRoute(page: BackgroundDocument.page),
        AutoRoute(page: ProofOfLegalStatus.page),
        AutoRoute(page: ContractorPdfViewer.page),
        AutoRoute(
          page: MainTabView.page,
          children: [
            AutoRoute(page: HomeView.page),
          ],
        ),
        AutoRoute(page: Chat.page),
        AutoRoute(page: Message.page),
      ];
}
