// ignore_for_file: prefer_const_constructors

import 'package:auto_route/auto_route.dart';
import 'package:shift/presentation/core/app_router.gr.dart';

@AutoRouterConfig()
class AppRouter extends RootStackRouter {
  final transitionsBuilder = TransitionsBuilders.slideLeft;
  final duration = 200;
  final reverseDuration = 20;

  CustomRoute _custom(
      {required PageInfo page,
      List<AutoRoute>? children,
      bool initial = false}) {
    return CustomRoute(
      page: page,
      initial: initial,
      transitionsBuilder: transitionsBuilder,
      durationInMilliseconds: duration,
      reverseDurationInMilliseconds: reverseDuration,
      children: children,
    );
  }

  @override
  List<AutoRoute> get routes => [
        _custom(
          page: SplashPage.page,
          initial: true,
        ),
        _custom(page: Onboarding1.page),
        _custom(page: Onboarding2.page),
        _custom(page: OnBoarding3.page),
        _custom(page: LoginPage.page),
        _custom(page: RegisterPage.page),
        _custom(page: RegisterProfilePage.page),
        _custom(page: LocationDetailForm.page),
        _custom(page: AddContractorSkillsForm.page),
        _custom(page: EducationListScreen.page),
        _custom(page: AddEducationDetailScreen.page),
        _custom(page: AddExperienceDetailScreen.page),
        _custom(page: ReferenceListScreen.page),
        _custom(page: AddReferenceDetailScreen.page),
        _custom(page: DocumentPageScreen.page),
        _custom(page: LegalScreeningQuestionsPage.page),
        _custom(page: TermsAndConditionsScreen.page),
        _custom(page: IntroVideoScreen.page),
        _custom(page: IntroQuizScreen.page),
        _custom(page: AddCardDetailPage.page),
        _custom(page: AddBankDetailsScreen.page),
        _custom(page: ViewHomeShiftDetails.page),
        _custom(page: ViewDates.page),
        _custom(page: HealthCarePostForm.page),
        _custom(page: HealthcarePostShift.page),
        _custom(page: ViewSingleApplicants.page),
        _custom(page: AddCardView.page),
        _custom(page: ViewApplicantProfile.page),
        _custom(page: ProfessionalReferenceDetail.page),
        _custom(page: PersonalReferenceDetail.page),
        _custom(page: CommonDocumentView.page),
        _custom(page: TotalPraposalView.page),
        _custom(page: ViewPersonPraposalView.page),
        _custom(page: CounterPurposeView.page),
        _custom(page: TeamsView.page),
        _custom(page: AddNewTeamView.page),
        _custom(page: TeamDetailView.page),
        _custom(page: AddNewMemberView.page),
        _custom(page: PostShiftRecurring.page),
        _custom(page: ReviewPostShiftDetail.page),
        _custom(page: PayableDetail.page),
        _custom(page: AddMultiDateTime.page),
        _custom(page: PrivacyPolicyScreen.page),
        _custom(page: AddSpecialityExperience.page),
        _custom(page: QuizResultScreen.page),
        // _custom(page: ShowGoogleMap.page),
        _custom(page: ContractorMainTabView.page),
        _custom(page: ContractorHomeView.page),
        _custom(page: SendProposal.page),
        _custom(page: ProposeAvailability.page),
        _custom(page: ContractorShiftView.page),
        _custom(page: ViewUpcomingShiftDetails.page),
        _custom(page: ViewContractorShift.page),
        _custom(page: ViewContractorShiftDates.page),
        _custom(page: PreviousShiftView.page),
        _custom(page: EditProfileView.page),
        _custom(page: ShiftActionsView.page),
        _custom(page: ProposalReceived.page),
        _custom(page: MyCalendarView.page),
        _custom(page: FilledHiredContractorList.page),
        _custom(page: AgreedProposal.page),
        _custom(page: SingleAgreedShift.page),
        _custom(page: MultiAgreedShift.page),
        _custom(page: ApprovedHiredList.page),
        _custom(page: CancelledContractorList.page),
        _custom(page: ProfessionalProfileView.page),
        _custom(page: PersonalProfileView.page),
        _custom(page: EducationProfileListView.page),
        _custom(page: EmployerAvailabilityView.page),
        _custom(page: HiredContractorView.page),
        _custom(page: EmployerLocationFormView.page),
        _custom(page: EmployerLocationView.page),
        _custom(page: ChangePasswordView.page),
        _custom(page: AccountManagementView.page),
        _custom(page: BillingView.page),
        _custom(page: InvoiceDetailView.page),
        _custom(page: InvoiceView.page),
        _custom(page: MonthlyStatementView.page),
        _custom(page: PaymentHistoryView.page),
        _custom(page: PaymentHistoryView.page),
        _custom(page: PaymentMethodView.page),
        _custom(page: PreviousShiftAllView.page),
        _custom(page: AboutView.page),
        _custom(page: CancellationPolicyView.page),
        _custom(page: FaqView.page),
        _custom(page: SupportTicketView.page),
        _custom(page: CustomerSupportView.page),
        _custom(page: ContractorEarningView.page),
        _custom(page: ContractorStatementView.page),
        _custom(page: ContractorTotalEarningView.page),
        _custom(page: ContractorWalletView.page),
        _custom(page: ContractorWithdrawPaymentView.page),
        _custom(page: ContractorPreviousShiftView.page),
        _custom(page: ContractorPerformanceInsightView.page),
        _custom(page: ContractorPerformanceInsightView.page),
        _custom(page: ContractorRatingView.page),
        _custom(page: ReferColleagueView.page),
        _custom(page: ContractorUpdateProfileView.page),
        _custom(page: BankListView.page),
        // _custom(page: FullTimePositionView.page),
        // _custom(page: FullPositionDetailView.page),

        _custom(
          page: EmployerFullPostingView.page,
        ),
        _custom(page: EmployerFullPostingConfirmView.page),
        _custom(page: EmployerFullPostingReviewView.page),
        _custom(page: EmployerFullPositionAddView.page),

        _custom(page: EmployerLongTermView.page),
        _custom(page: EmployerLongTermPositionDetailView.page),
        _custom(page: EmployerLongTermPositionAddView.page),
        _custom(page: EmployerLongTermPositionAddDetailView.page),
        _custom(page: EmployerLongTermApplicantView.page),
        _custom(page: EmployerLongTermPostConfirmationView.page),
        _custom(page: EmployerLongTermReviewDetailView.page),
        _custom(page: EmployerLongTermPayableView.page),
        _custom(page: EmployerLongTermAuthorizePaymentView.page),
        _custom(page: EmployerFullPositionApplicantsView.page),
        _custom(page: EmployerFullPositionPositionDetailView.page),

        _custom(page: ContractorFullTimePositionView.page),
        _custom(page: ContractorLongTermView.page),

        _custom(page: EmployerCompletedShiftView.page),
        _custom(page: SaveTemplateView.page),
        _custom(page: ViewCollegueProfile.page),
        _custom(page: AddressProofScreen.page),
        _custom(page: BackgroundDocument.page),
        _custom(page: ProofOfLegalStatus.page),
        _custom(page: ContractorPdfViewer.page),
        _custom(page: ContractorEditProfile.page),
        _custom(
          page: MainTabView.page,
          children: [
            _custom(page: HomeView.page),
          ],
        ),
        _custom(page: Chat.page),
        _custom(page: Message.page),
        _custom(page: Viewmedia.page),
        _custom(page: NotificationView.page),
        _custom(page: CompleteShiftInvoiceView.page),
        _custom(page: ContractorProposedAvailability.page),
        _custom(page: LongTermHiredContractorList.page),
      ];
}
