# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  # pod 'BSImagePicker'
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      if target.name == 'Runner'
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'YES'
        config.build_settings['CODE_SIGNING_IDENTITY'] = 'Apple Development'
        config.build_settings['DEVELOPMENT_TEAM'] = '6F7ZM56Y52' # Your Apple Team ID
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = 'ShiftFinder Profile'
      else
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['CODE_SIGNING_IDENTITY'] = ''
        config.build_settings.delete('PROVISIONING_PROFILE_SPECIFIER')
      end
      # You can remove unused permissions here
      # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
  '$(inherited)',

  ## dart: PermissionGroup.camera
  'PERMISSION_CAMERA=1',

  ## dart: PermissionGroup.microphone
  # 'PERMISSION_MICROPHONE=1',

  ## dart: PermissionGroup.photos
  'PERMISSION_PHOTOS=1',

  ## dart: PermissionGroup.notification
  'PERMISSION_NOTIFICATIONS=1',

  ## dart: PermissionGroup.mediaLibrary
  'PERMISSION_MEDIA_LIBRARY=1',

  ## dart: PermissionGroup.location
  'PERMISSION_LOCATION=1'
]

    end
  end
end
