// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'post_shift_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$PostShiftDTOImpl _$$PostShiftDTOImplFromJson(Map<String, dynamic> json) =>
    _$PostShiftDTOImpl(
      update_status: (json['update_status'] as num?)?.toInt(),
      id: (json['id'] as num?)?.toInt(),
      roles_list_id: json['roles_list_id'] as String?,
      specialties_detail_id: json['specialties_detail_id'] as String?,
      specialties_detail_other: json['specialties_detail_other'] as String?,
      softwares_skill_list_id: json['softwares_skill_list_id'] as String?,
      software_skill_other: json['software_skill_other'] as String?,
      languages_list_id: json['languages_list_id'] as String?,
      language_other: json['language_other'] as String?,
      location_id: json['location_id'] as String?,
      location_unit: json['location_unit'] as String?,
      rate_hour: (json['rate_hour'] as num?)?.toDouble(),
      recurring_status: json['recurring_status'] as String?,
      start_date: json['start_date'] as String?,
      recurrence_mode: (json['recurrence_mode'] as num?)?.toInt(),
      days: json['days'] as String?,
      end_date: json['end_date'] as String?,
      disclaimer: json['disclaimer'] as String?,
      share_team_status: json['share_team_status'] as String?,
      team_id: json['team_id'] as String?,
      save_template_status: json['save_template_status'] as String?,
      shift_type: (json['shift_type'] as num?)?.toInt(),
      date: json['date'] as String?,
      same_or_different_time: (json['same_or_different_time'] as num?)?.toInt(),
      start_time: json['start_time'] as String?,
      end_time: json['end_time'] as String?,
      unpaid_break_id: (json['unpaid_break_id'] as num?)?.toInt(),
      total_payable_hour: json['total_payable_hour'] as String?,
      commute_allowance_type: (json['commute_allowance_type'] as num?)?.toInt(),
      commute_allowance: json['commute_allowance'] as String?,
      accommodation_allowance_type:
          (json['accommodation_allowance_type'] as num?)?.toInt(),
      accommodation_allowance: json['accommodation_allowance'] as String?,
      individual_shift: (json['individual_shift'] as num?)?.toInt(),
      shift_note: json['shift_note'] as String?,
      vacancie_type: json['vacancie_type'] as String?,
      number_of_vacancie: (json['number_of_vacancie'] as num?)?.toInt(),
      recurrence_id: (json['recurrence_id'] as num?)?.toInt(),
      recurring_start_date: json['recurring_start_date'] as String?,
      recurring_end_date: json['recurring_end_date'] as String?,
      multi_date: json['multi_date'] as String?,
    );

Map<String, dynamic> _$$PostShiftDTOImplToJson(_$PostShiftDTOImpl instance) =>
    <String, dynamic>{
      'update_status': instance.update_status,
      'id': instance.id,
      'roles_list_id': instance.roles_list_id,
      'specialties_detail_id': instance.specialties_detail_id,
      'specialties_detail_other': instance.specialties_detail_other,
      'softwares_skill_list_id': instance.softwares_skill_list_id,
      'software_skill_other': instance.software_skill_other,
      'languages_list_id': instance.languages_list_id,
      'language_other': instance.language_other,
      'location_id': instance.location_id,
      'location_unit': instance.location_unit,
      'rate_hour': instance.rate_hour,
      'recurring_status': instance.recurring_status,
      'start_date': instance.start_date,
      'recurrence_mode': instance.recurrence_mode,
      'days': instance.days,
      'end_date': instance.end_date,
      'disclaimer': instance.disclaimer,
      'share_team_status': instance.share_team_status,
      'team_id': instance.team_id,
      'save_template_status': instance.save_template_status,
      'shift_type': instance.shift_type,
      'date': instance.date,
      'same_or_different_time': instance.same_or_different_time,
      'start_time': instance.start_time,
      'end_time': instance.end_time,
      'unpaid_break_id': instance.unpaid_break_id,
      'total_payable_hour': instance.total_payable_hour,
      'commute_allowance_type': instance.commute_allowance_type,
      'commute_allowance': instance.commute_allowance,
      'accommodation_allowance_type': instance.accommodation_allowance_type,
      'accommodation_allowance': instance.accommodation_allowance,
      'individual_shift': instance.individual_shift,
      'shift_note': instance.shift_note,
      'vacancie_type': instance.vacancie_type,
      'number_of_vacancie': instance.number_of_vacancie,
      'recurrence_id': instance.recurrence_id,
      'recurring_start_date': instance.recurring_start_date,
      'recurring_end_date': instance.recurring_end_date,
      'multi_date': instance.multi_date,
    };
